## autoUpdater.yml
name: 'autoUpdater'

on:
  push:
  schedule:
    - cron: '0 */3 * * *' # update every 3 hours at :10

jobs:
  updater:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout Notes repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install beautifulsoup4
          pip3 install requests
      - name: move old to backup and generate new menus
        run: |
          python -c 'import Dining_Hall_scrapper; Dining_Hall_scrapper.github_autoUpdater()'
      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit and push if changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated Update
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
