## autoUpdater.yml
name: 'autoUpdater'

on:
  push:
  schedule:
    - cron: '0 8 * * *' # UTC 8:00 = UTC-5 3:00

jobs:
  updater:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout Notes repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install beautifulsoup4
          pip3 install requests
      - name: move old to backup and generate new menus
        run: |
          python -c 'import Dining_Hall_scrapper; Dining_Hall_scrapper.github_autoUpdater()'

      - name: Commit and push if changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Daily Update
