## autoUpdater.yml
name: 'autoUpdater'

on:
  push:
  schedule:
    - cron: '0 2 * * *' # UTC 2:00 = UTC-5 7:00

jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Notes repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo pip3 install beautifulsoup4
      - name: move old to backup and generate new menus
        run: |
          python -c 'import Dining_Hall_scrapper; Dining_Hall_scrapper.github_autoUpdater()'

      - name: Commit and push if changes
        run: |
          git config --global user.email "ljk5403@outlook.com"
          git config --global user.name "AutoUpdater"
          git add data.txt
          git commit -m "Updated menu." || exit 0  # Exit gracefully if no changes
          git push
